ssh_key             = ""
ssh_key_name        = "cmtr-ygbit6f1-keypair"
aws_region          = "eu-west-1"
vpc_name            = "cmtr-ygbit6f1-vpc"
security_group_name = "cmtr-ygbit6f1-sg"
project_name        = "epam-tf-lab"
